import Font from "@/models/Font";

export const fontNames = [
  "Nunito",
  "Bangers",
  "Chewy",
  "Comic Neue",
  "Freckle Face",
  "Kablammo",
  "Monoton",
  "Rubik Bubbles",
  "Rubik Glitch",
  "Silkscreen",
  "Fredoka",
  "Luckiest Guy",
  "Permanent Marker",
  "Press Start 2P",
  "Righteous",
  "Orbitron",
  "Caveat",
  "Pacifico",
  "Bungee",
  "Special Elite",
  "Anton",
  "Archivo Black",
  "Audiowide",
  "Black Ops One",
  "Boogaloo",
  "Carter One",
  "Cinzel",
  "DM Serif Display",
  "Exo 2",
  "Faster One",
  "Fugaz One",
  "Graduate",
  "Knewave",
  "Merienda",
  "Playfair Display",
  "Poiret One",
  "Prata",
  "Rubik Dirt",
  "Space Mono",
  "Titan One",
  "Unbounded",
  "VT323",
  "Bebas Neue",
  "Changa One",
  "Codystar",
  "Coiny",
  "DynaPuff",
  "Finger Paint",
  "Flavors",
  "Germania One",
  "Henny Penny",
  "Jolly Lodger",
  "Major Mono Display",
  "Metal Mania",
  "New Rocker",
  "Oleo Script",
  "Oxanium",
  "Pirata One",
  "Plaster",
  "Rammetto One",
  "Rancho",
  "Rye",
  "Shojumaru",
  "Slackey",
  "Tilt Neon",
  "Trade Winds",
  "Wallpoet",
  "Zilla Slab Highlight",
] as const;

const fonts: Record<string, Font> = {
  Nunito: {
    name: "Nunito",
    cssVariable: "--font-nunito",
    fallback: "system-ui, sans-serif",
    vibe: "Default friendly utility mode.",
    sample: "CommonFunLib keeps it comfy.",
  },
  Bangers: {
    name: "Bangers",
    cssVariable: "--font-bangers",
    fallback: "Impact, fantasy",
    vibe: "Comic book button smashing.",
    sample: "Zap! Hash that string!",
  },
  Chewy: {
    name: "Chewy",
    cssVariable: "--font-chewy",
    fallback: "cursive",
    vibe: "Soft marshmallow chaos.",
    sample: "Squish the payload gently.",
  },
  "Comic Neue": {
    name: "Comic Neue",
    cssVariable: "--font-comic-neue",
    fallback: "cursive",
    vibe: "Goofy, but still house-trained.",
    sample: "Utilities, but make it doodly.",
  },
  "Freckle Face": {
    name: "Freckle Face",
    cssVariable: "--font-freckle-face",
    fallback: "cursive",
    vibe: "Lunchbox sticker energy.",
    sample: "Generate a name, maybe three.",
  },
  Kablammo: {
    name: "Kablammo",
    cssVariable: "--font-kablammo",
    fallback: "fantasy",
    vibe: "Maximum cartoon voltage.",
    sample: "KABLAMMO! API online!",
  },
  Monoton: {
    name: "Monoton",
    cssVariable: "--font-monoton",
    fallback: "fantasy",
    vibe: "Neon arcade marquee.",
    sample: "Convert all the things.",
  },
  "Rubik Bubbles": {
    name: "Rubik Bubbles",
    cssVariable: "--font-rubik-bubbles",
    fallback: "fantasy",
    vibe: "Inflatable pool float letters.",
    sample: "Bubble sort? No thanks.",
  },
  "Rubik Glitch": {
    name: "Rubik Glitch",
    cssVariable: "--font-rubik-glitch",
    fallback: "fantasy",
    vibe: "Very legal terminal incident.",
    sample: "404: boring font not found.",
  },
  Silkscreen: {
    name: "Silkscreen",
    cssVariable: "--font-silkscreen",
    fallback: "monospace",
    vibe: "Tiny pixel dashboard.",
    sample: "STATUS: ABSOLUTELY FINE",
  },
  Fredoka: {
    name: "Fredoka",
    cssVariable: "--font-fredoka",
    fallback: "system-ui, sans-serif",
    vibe: "Round, bouncy control panel.",
    sample: "Buttons should feel like candy.",
  },
  "Luckiest Guy": {
    name: "Luckiest Guy",
    cssVariable: "--font-luckiest-guy",
    fallback: "Impact, fantasy",
    vibe: "Prize wheel headline energy.",
    sample: "Lucky roll, lucky result.",
  },
  "Permanent Marker": {
    name: "Permanent Marker",
    cssVariable: "--font-permanent-marker",
    fallback: "cursive",
    vibe: "Whiteboard notes after midnight.",
    sample: "Ship it, then underline it twice.",
  },
  "Press Start 2P": {
    name: "Press Start 2P",
    cssVariable: "--font-press-start-2p",
    fallback: "monospace",
    vibe: "Arcade cabinet status text.",
    sample: "INSERT API TOKEN",
  },
  Righteous: {
    name: "Righteous",
    cssVariable: "--font-righteous",
    fallback: "fantasy",
    vibe: "Retro-future utility chrome.",
    sample: "Convert with style and confidence.",
  },
  Orbitron: {
    name: "Orbitron",
    cssVariable: "--font-orbitron",
    fallback: "sans-serif",
    vibe: "Space station command deck.",
    sample: "SYSTEMS READY FOR LAUNCH",
  },
  Caveat: {
    name: "Caveat",
    cssVariable: "--font-caveat",
    fallback: "cursive",
    vibe: "Handwritten sticky note charm.",
    sample: "Remember to hash the secret.",
  },
  Pacifico: {
    name: "Pacifico",
    cssVariable: "--font-pacifico",
    fallback: "cursive",
    vibe: "Smooth surf-shop signage.",
    sample: "Encode it and ride the wave.",
  },
  Bungee: {
    name: "Bungee",
    cssVariable: "--font-bungee",
    fallback: "fantasy",
    vibe: "Chunky street sign swagger.",
    sample: "TOOLS OPEN ALL NIGHT",
  },
  "Special Elite": {
    name: "Special Elite",
    cssVariable: "--font-special-elite",
    fallback: "monospace",
    vibe: "Typewriter mystery terminal.",
    sample: "Case file: function accepted.",
  },
  Anton: {
    name: "Anton",
    cssVariable: "--font-anton",
    fallback: "Impact, sans-serif",
    vibe: "Compressed poster punch.",
    sample: "LOUD UTILS, CLEAN OUTPUT.",
  },
  "Archivo Black": {
    name: "Archivo Black",
    cssVariable: "--font-archivo-black",
    fallback: "Arial Black, sans-serif",
    vibe: "Heavy dashboard signage.",
    sample: "Every result lands with weight.",
  },
  Audiowide: {
    name: "Audiowide",
    cssVariable: "--font-audiowide",
    fallback: "fantasy",
    vibe: "Chrome arcade dashboard.",
    sample: "Transmit the converter beam.",
  },
  "Black Ops One": {
    name: "Black Ops One",
    cssVariable: "--font-black-ops-one",
    fallback: "Impact, fantasy",
    vibe: "Mission briefing title card.",
    sample: "OPERATION: FORMAT PAYLOAD",
  },
  Boogaloo: {
    name: "Boogaloo",
    cssVariable: "--font-boogaloo",
    fallback: "cursive",
    vibe: "Loose retro cartoon bounce.",
    sample: "Generate names with a wink.",
  },
  "Carter One": {
    name: "Carter One",
    cssVariable: "--font-carter-one",
    fallback: "fantasy",
    vibe: "Chunky sign-painter confidence.",
    sample: "Common functions, uncommon flavor.",
  },
  Cinzel: {
    name: "Cinzel",
    cssVariable: "--font-cinzel",
    fallback: "serif",
    vibe: "Ancient plaque meets API docs.",
    sample: "The hash shall be remembered.",
  },
  "DM Serif Display": {
    name: "DM Serif Display",
    cssVariable: "--font-dm-serif-display",
    fallback: "Georgia, serif",
    vibe: "Editorial elegance mode.",
    sample: "A refined little utility suite.",
  },
  "Exo 2": {
    name: "Exo 2",
    cssVariable: "--font-exo-2",
    fallback: "sans-serif",
    vibe: "Technical sci-fi console.",
    sample: "Calibrate, convert, compute.",
  },
  "Faster One": {
    name: "Faster One",
    cssVariable: "--font-faster-one",
    fallback: "fantasy",
    vibe: "Speed lines on every label.",
    sample: "Zero to encoded in one click.",
  },
  "Fugaz One": {
    name: "Fugaz One",
    cssVariable: "--font-fugaz-one",
    fallback: "fantasy",
    vibe: "Slanted weekend scoreboard.",
    sample: "Tools with a little lean.",
  },
  Graduate: {
    name: "Graduate",
    cssVariable: "--font-graduate",
    fallback: "serif",
    vibe: "Varsity utility jacket.",
    sample: "Class of reliable helpers.",
  },
  Knewave: {
    name: "Knewave",
    cssVariable: "--font-knewave",
    fallback: "cursive",
    vibe: "Brushy sticker headline.",
    sample: "Paste it, twist it, done.",
  },
  Merienda: {
    name: "Merienda",
    cssVariable: "--font-merienda",
    fallback: "cursive",
    vibe: "Friendly handwritten flourish.",
    sample: "A warm cup of helper functions.",
  },
  "Playfair Display": {
    name: "Playfair Display",
    cssVariable: "--font-playfair-display",
    fallback: "Georgia, serif",
    vibe: "Fancy magazine utility spread.",
    sample: "Developer tools, dressed nicely.",
  },
  "Poiret One": {
    name: "Poiret One",
    cssVariable: "--font-poiret-one",
    fallback: "sans-serif",
    vibe: "Thin art-deco interface labels.",
    sample: "Minimal lines, maximal charm.",
  },
  Prata: {
    name: "Prata",
    cssVariable: "--font-prata",
    fallback: "Georgia, serif",
    vibe: "Polished boutique typography.",
    sample: "Elegant output, no drama.",
  },
  "Rubik Dirt": {
    name: "Rubik Dirt",
    cssVariable: "--font-rubik-dirt",
    fallback: "fantasy",
    vibe: "Grainy stamped label energy.",
    sample: "Rough edges, clean responses.",
  },
  "Space Mono": {
    name: "Space Mono",
    cssVariable: "--font-space-mono",
    fallback: "monospace",
    vibe: "Friendly orbital monospace.",
    sample: "const answer = ready;",
  },
  "Titan One": {
    name: "Titan One",
    cssVariable: "--font-titan-one",
    fallback: "fantasy",
    vibe: "Bubble-bold command buttons.",
    sample: "SMASH THE CONVERT BUTTON",
  },
  Unbounded: {
    name: "Unbounded",
    cssVariable: "--font-unbounded",
    fallback: "sans-serif",
    vibe: "Wide futuristic control labels.",
    sample: "Utilities beyond the edge.",
  },
  VT323: {
    name: "VT323",
    cssVariable: "--font-vt323",
    fallback: "monospace",
    vibe: "Old terminal, new tricks.",
    sample: "> function loaded successfully",
  },
  "Bebas Neue": {
    name: "Bebas Neue",
    cssVariable: "--font-bebas-neue",
    fallback: "Impact, sans-serif",
    vibe: "Tall poster headline snap.",
    sample: "UTILITY MODE ENGAGED",
  },
  "Changa One": {
    name: "Changa One",
    cssVariable: "--font-changa-one",
    fallback: "fantasy",
    vibe: "Squashy arcade announcer.",
    sample: "Randomize the whole vibe.",
  },
  Codystar: {
    name: "Codystar",
    cssVariable: "--font-codystar",
    fallback: "fantasy",
    vibe: "Outlined marquee lights.",
    sample: "Blink twice, then convert.",
  },
  Coiny: {
    name: "Coiny",
    cssVariable: "--font-coiny",
    fallback: "fantasy",
    vibe: "Rounded sticker-shop bold.",
    sample: "One click, shiny result.",
  },
  DynaPuff: {
    name: "DynaPuff",
    cssVariable: "--font-dynapuff",
    fallback: "cursive",
    vibe: "Soft inflated marker letters.",
    sample: "Make the buttons bounce.",
  },
  "Finger Paint": {
    name: "Finger Paint",
    cssVariable: "--font-finger-paint",
    fallback: "cursive",
    vibe: "Painted playground labels.",
    sample: "Smudge the boring away.",
  },
  Flavors: {
    name: "Flavors",
    cssVariable: "--font-flavors",
    fallback: "fantasy",
    vibe: "Melting candy signage.",
    sample: "Sweet output, zero stickiness.",
  },
  "Germania One": {
    name: "Germania One",
    cssVariable: "--font-germania-one",
    fallback: "serif",
    vibe: "Old-world title stamp.",
    sample: "An ancient tool awakens.",
  },
  "Henny Penny": {
    name: "Henny Penny",
    cssVariable: "--font-henny-penny",
    fallback: "cursive",
    vibe: "Wiggly storybook header.",
    sample: "The payload took a detour.",
  },
  "Jolly Lodger": {
    name: "Jolly Lodger",
    cssVariable: "--font-jolly-lodger",
    fallback: "fantasy",
    vibe: "Spooky carnival placard.",
    sample: "Boo: your hash is ready.",
  },
  "Major Mono Display": {
    name: "Major Mono Display",
    cssVariable: "--font-major-mono-display",
    fallback: "monospace",
    vibe: "Wide geometric terminal.",
    sample: "mono tools, major mood",
  },
  "Metal Mania": {
    name: "Metal Mania",
    cssVariable: "--font-metal-mania",
    fallback: "fantasy",
    vibe: "Heavy-riff title cards.",
    sample: "Shred the encoding queue.",
  },
  "New Rocker": {
    name: "New Rocker",
    cssVariable: "--font-new-rocker",
    fallback: "fantasy",
    vibe: "Blackletter stage banner.",
    sample: "Rock the common functions.",
  },
  "Oleo Script": {
    name: "Oleo Script",
    cssVariable: "--font-oleo-script",
    fallback: "cursive",
    vibe: "Thick sunny script.",
    sample: "A smooth helper swirl.",
  },
  Oxanium: {
    name: "Oxanium",
    cssVariable: "--font-oxanium",
    fallback: "sans-serif",
    vibe: "Angular esports console.",
    sample: "Queue locked. Tools online.",
  },
  "Pirata One": {
    name: "Pirata One",
    cssVariable: "--font-pirata-one",
    fallback: "fantasy",
    vibe: "Treasure-map command text.",
    sample: "X marks the endpoint.",
  },
  Plaster: {
    name: "Plaster",
    cssVariable: "--font-plaster",
    fallback: "fantasy",
    vibe: "Stencil poster spectacle.",
    sample: "CUTOUT LETTERS, BIG RESULT",
  },
  "Rammetto One": {
    name: "Rammetto One",
    cssVariable: "--font-rammetto-one",
    fallback: "fantasy",
    vibe: "Oversized bubble authority.",
    sample: "Maximum rounded confidence.",
  },
  Rancho: {
    name: "Rancho",
    cssVariable: "--font-rancho",
    fallback: "cursive",
    vibe: "Casual brush-sign ease.",
    sample: "Round up the helpers.",
  },
  Rye: {
    name: "Rye",
    cssVariable: "--font-rye",
    fallback: "serif",
    vibe: "Vintage saloon label.",
    sample: "Encode at high noon.",
  },
  Shojumaru: {
    name: "Shojumaru",
    cssVariable: "--font-shojumaru",
    fallback: "fantasy",
    vibe: "Sharp comic title strike.",
    sample: "Slice through the payload.",
  },
  Slackey: {
    name: "Slackey",
    cssVariable: "--font-slackey",
    fallback: "fantasy",
    vibe: "Chunky lazy-day lettering.",
    sample: "No rush, still instant.",
  },
  "Tilt Neon": {
    name: "Tilt Neon",
    cssVariable: "--font-tilt-neon",
    fallback: "sans-serif",
    vibe: "Bent tube sign glow.",
    sample: "Neon output in progress.",
  },
  "Trade Winds": {
    name: "Trade Winds",
    cssVariable: "--font-trade-winds",
    fallback: "fantasy",
    vibe: "Windblown adventure title.",
    sample: "Set sail for JSON.",
  },
  Wallpoet: {
    name: "Wallpoet",
    cssVariable: "--font-wallpoet",
    fallback: "fantasy",
    vibe: "Blocky digital mural.",
    sample: "Paint the terminal wall.",
  },
  "Zilla Slab Highlight": {
    name: "Zilla Slab Highlight",
    cssVariable: "--font-zilla-slab-highlight",
    fallback: "serif",
    vibe: "Highlighted slab display.",
    sample: "Mark the result important.",
  },
};

export const getFont = (fontName: string): Font => fonts[fontName] || fonts.Nunito;

export const getFonts = () => fontNames.map((name) => getFont(name));
