const CommonFunctions = require("./Lib/CommonFunctions");
const Generator = require("./Lib/Generator");
const Converter = require("./Lib/Converter");
const Hashing = require("./Lib/Hashing");

const generator = new Generator();
const converter = new Converter();

const common = {
  isEven: CommonFunctions.isEven,
  isOdd: CommonFunctions.isOdd,
  factorial: CommonFunctions.factorial,
  gcd: CommonFunctions.gcd,
  lcm: CommonFunctions.lcm,
  isPrime: CommonFunctions.isPrime,
  swapVariableValue: CommonFunctions.swapVariableValue,
  reverseString: CommonFunctions.reverseString,
  isPalindrome: CommonFunctions.isPalindrome,
  slugify: CommonFunctions.slugify,
  clamp: CommonFunctions.clamp,
  percentage: CommonFunctions.percentage,
  fibonacci: CommonFunctions.fibonacci,
  average: CommonFunctions.average,
  median: CommonFunctions.median,
  titleCase: CommonFunctions.titleCase,
  wordCount: CommonFunctions.wordCount,
};

const generate = {
  randomNumber: (min = 1, max = 100) => generator.generateRandomNumber(min, max),
  randomName: () => generator.generateRandomName(),
  firstNames: () => generator.getFirstNames(),
  lastNames: () => generator.getLastNames(),
  password: (length = 12) => generator.generatePassword(length),
  uuid: () => generator.generateUuid(),
  token: (bytes = 16) => generator.generateToken(bytes),
  pin: (digits = 6) => generator.generatePin(digits),
  color: () => generator.generateColor(),
  lorem: (words = 24) => generator.generateLorem(words),
  nanoid: (length = 21) => generator.generateNanoId(length),
  apiKey: (prefix = "cfl", bytes = 24) => generator.generateApiKey(prefix, bytes),
  macAddress: () => generator.generateMacAddress(),
  semver: (major = 0) => generator.generateSemver(major),
  timestamp: (format = "iso") => generator.generateTimestamp(format),
};

const convert = {
  fetchExchangeRates: () => converter.fetchExchangeRates(),
  currency: (amount, fromCurrency, toCurrency) =>
    converter.convertCurrency(amount, fromCurrency, toCurrency),
  length: (length, fromUnit, toUnit) => converter.convertLength(length, fromUnit, toUnit),
  weight: (weight, fromUnit, toUnit) => converter.convertWeight(weight, fromUnit, toUnit),
  area: (area, fromUnit, toUnit) => converter.convertArea(area, fromUnit, toUnit),
  dataSize: (value, fromUnit, toUnit) => converter.convertDataSize(value, fromUnit, toUnit),
  speed: (value, fromUnit, toUnit) => converter.convertSpeed(value, fromUnit, toUnit),
  temperature: (temperature, fromUnit, toUnit) =>
    converter.convertTemperature(temperature, fromUnit, toUnit),
  lengthSystem: (value, fromSystem, toSystem) =>
    converter.convertLengthSystem(value, fromSystem, toSystem),
  numberBase: (value, fromBase, toBase) =>
    converter.convertNumberBase(value, fromBase, toBase),
  duration: (value, fromUnit, toUnit) => converter.convertDuration(value, fromUnit, toUnit),
  timestamp: (value, fromUnit, toUnit) =>
    converter.convertTimestamp(value, fromUnit, toUnit),
  color: (value, fromFormat, toFormat) => converter.convertColor(value, fromFormat, toFormat),
};

const hash = {
  md5: Hashing.md5,
  sha1: Hashing.sha1,
  sha256: Hashing.sha256,
  sha384: Hashing.sha384,
  sha512: Hashing.sha512,
  sha3_256: Hashing.sha3_256,
  sha3_512: Hashing.sha3_512,
  base64Encode: Hashing.base64Encode,
  base64Decode: Hashing.base64Decode,
  hmacSha256: Hashing.hmacSha256,
  hmacSha512: Hashing.hmacSha512,
  base64UrlEncode: Hashing.base64UrlEncode,
  base64UrlDecode: Hashing.base64UrlDecode,
  checksum: Hashing.checksum,
};

const api = {
  CommonFunctions,
  Generator,
  Converter,
  Hashing,
  common,
  generate,
  convert,
  hash,
  isEven: common.isEven,
  isOdd: common.isOdd,
  factorial: common.factorial,
  gcd: common.gcd,
  lcm: common.lcm,
  isPrime: common.isPrime,
  swapVariableValue: common.swapVariableValue,
  reverseString: common.reverseString,
  isPalindrome: common.isPalindrome,
  slugify: common.slugify,
  clamp: common.clamp,
  percentage: common.percentage,
  fibonacci: common.fibonacci,
  average: common.average,
  median: common.median,
  titleCase: common.titleCase,
  wordCount: common.wordCount,
  generateRandomNumber: generate.randomNumber,
  generateRandomName: generate.randomName,
  getFirstNames: generate.firstNames,
  getLastNames: generate.lastNames,
  generatePassword: generate.password,
  generateUuid: generate.uuid,
  generateToken: generate.token,
  generatePin: generate.pin,
  generateColor: generate.color,
  generateLorem: generate.lorem,
  generateNanoId: generate.nanoid,
  generateApiKey: generate.apiKey,
  generateMacAddress: generate.macAddress,
  generateSemver: generate.semver,
  generateTimestamp: generate.timestamp,
  fetchExchangeRates: convert.fetchExchangeRates,
  convertCurrency: convert.currency,
  convertLength: convert.length,
  convertWeight: convert.weight,
  convertArea: convert.area,
  convertDataSize: convert.dataSize,
  convertSpeed: convert.speed,
  convertTemperature: convert.temperature,
  convertLengthSystem: convert.lengthSystem,
  convertNumberBase: convert.numberBase,
  convertDuration: convert.duration,
  convertTimestamp: convert.timestamp,
  convertColor: convert.color,
  md5: hash.md5,
  sha1: hash.sha1,
  sha256: hash.sha256,
  sha384: hash.sha384,
  sha512: hash.sha512,
  sha3_256: hash.sha3_256,
  sha3_512: hash.sha3_512,
  base64Encode: hash.base64Encode,
  base64Decode: hash.base64Decode,
  hmacSha256: hash.hmacSha256,
  hmacSha512: hash.hmacSha512,
  base64UrlEncode: hash.base64UrlEncode,
  base64UrlDecode: hash.base64UrlDecode,
  checksum: hash.checksum,
};

module.exports = api;
module.exports.default = api;
